application: resume
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: resume.app
